(function(){
  const D=window.CAREER_DATA;
  const KEY='vikas-career-pro-v2';
  const defaultState={lessons:{},practiceAnswers:[],practiceIndex:0,interviewIndex:0,interviewResults:[],projects:{},revisionDone:{},jobs:[],pbiIndex:0};
  let state=load(); let interviewChecked=false; let practiceAnswered=false; let pbiAnswered=false;
  const $=id=>document.getElementById(id);
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  function load(){try{return Object.assign({},defaultState,JSON.parse(localStorage.getItem(KEY)||'null')||{})}catch{return {...defaultState}}}
  function save(){localStorage.setItem(KEY,JSON.stringify(state));renderAllStats()}
  function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),1800)}
  function nav(view){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===view));document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.go===view));$('moreSheet').classList.add('hidden');window.scrollTo({top:0,behavior:'smooth'});renderView(view)}
  function renderView(v){if(v==='home')renderHome();if(v==='learn')renderLessons();if(v==='practice')renderPractice();if(v==='interview')renderInterview();if(v==='sql')renderSql();if(v==='powerbi')renderPbi();if(v==='projects')renderProjects();if(v==='revision')renderRevision();if(v==='jobs')renderJobs();if(v==='profile')renderProfile()}
  document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.go)));
  $('moreFloating').onclick=()=>$('moreSheet').classList.remove('hidden');$('closeSheet').onclick=()=>$('moreSheet').classList.add('hidden');$('moreSheet').addEventListener('click',e=>{if(e.target.id==='moreSheet')$('moreSheet').classList.add('hidden')});
  $('resetBtn').onclick=()=>{if(confirm('Reset all local V2 progress and jobs?')){localStorage.removeItem(KEY);state=load();toast('Progress reset');renderAll()}};

  function calcOverall(){const lesson=Object.keys(state.lessons).filter(k=>state.lessons[k]).length/D.lessons.length;const practice=state.practiceAnswers.length?state.practiceAnswers.filter(Boolean).length/D.practice.length:0;const interview=state.interviewResults.length?state.interviewResults.reduce((a,b)=>a+b,0)/(D.interview.length*100):0;const projects=Object.values(state.projects).reduce((a,x)=>a+(x?.stepsDone?.length||0),0)/(D.projects.length*6);return Math.round((lesson*.35+practice*.2+interview*.25+projects*.2)*100)}
  function renderAllStats(){const pct=calcOverall();$('heroProgress').textContent=pct+'%';const heroRing=document.querySelector('.hero-ring'); if(heroRing) heroRing.style.background='';$('lessonStat').textContent=Object.values(state.lessons).filter(Boolean).length+'/'+D.lessons.length;$('scoreStat').textContent=state.interviewResults.length?Math.round(state.interviewResults.reduce((a,b)=>a+b,0)/state.interviewResults.length)+'%':'0%';$('jobStat').textContent=state.jobs.length;$('streakStat').textContent='1 day';$('missionBar').style.width=(state.lessons.sql?100:0)+'%'}
  function renderHome(){renderAllStats();const pct=calcOverall();const ring=document.querySelector('.hero-ring');const deg=Math.round(pct*3.6);ring.style.background=`radial-gradient(circle at center,#0c1222 56%,transparent 57%),conic-gradient(var(--accent) ${deg}deg,rgba(255,255,255,.08) ${deg}deg)`;$('roadmapHome').innerHTML=D.lessons.map(l=>{const done=!!state.lessons[l.id];const v=done?100:0;return `<div class="road-mini panel"><div><strong>${l.title}</strong><span>${l.tag} · ${done?'Complete':'Not started'}</span><div class="bar"><i style="width:${v}%"></i></div></div><span class="pill ${done?'purple':''}">${done?'Done':'Start'}</span></div>`}).join('');
    if(state.lessons.sql){$('nextActionTitle').textContent='Now prove it in interview mode';$('nextActionStrong').textContent='Explain SQL JOINs without looking at notes.';$('nextActionText').textContent='Use a definition, say which rows are preserved, and give one business example.'}else{$('nextActionTitle').textContent='Build your first win';$('nextActionStrong').textContent='Finish the SQL JOIN lesson today.';$('nextActionText').textContent='Then take one practice question so the concept moves from reading to recall.'}}

  function renderLessons(){const list=$('lessonList');list.innerHTML=D.lessons.map(l=>{const done=!!state.lessons[l.id];return `<button class="lesson-card panel" data-lesson="${l.id}" type="button"><div><span class="pill ${l.tag==='SQL'?'blue':'purple'}">${l.tag}</span><h3>${l.title}</h3><p>${l.desc}</p></div><span class="tag">${done?'Done':'Start'} · ${l.time}</span></button>`}).join('');list.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>showLesson(b.dataset.lesson))}
  function showLesson(id){const l=D.lessons.find(x=>x.id===id);const d=$('lessonDetail');d.classList.remove('hidden');d.innerHTML=`<div class="eyebrow">${l.tag}</div><h3>${l.title}</h3><p>${l.body}</p><div class="example">${esc(l.example)}</div><div class="revision-question"><b>Recall:</b> ${l.recall}</div><button id="completeLesson" class="btn primary full" type="button">${state.lessons[l.id]?'Completed':'Mark lesson complete'}</button>`;if(state.lessons[l.id])$('completeLesson').disabled=true;$('completeLesson').onclick=()=>{state.lessons[l.id]=true;save();renderLessons();renderHome();d.classList.add('hidden');toast('Lesson completed ✓')}}

  function renderPractice(){const i=state.practiceIndex%D.practice.length,q=D.practice[i];practiceAnswered=state.practiceAnswers[i]!==undefined;$('practiceTopic').textContent=q.topic;$('practiceIndex').textContent=`${i+1} / ${D.practice.length}`;$('practiceQuestion').textContent=q.q;const opts=$('practiceOptions');opts.innerHTML=q.options.map((o,n)=>`<button class="answer ${practiceAnswered?(n===q.correct?'correct':n===state.practiceAnswers[i]?'wrong':''):''}" data-answer="${n}" type="button" ${practiceAnswered?'disabled':''}>${esc(o)}</button>`).join('');$('practiceFeedback').classList.toggle('hidden',!practiceAnswered);if(practiceAnswered){$('practiceFeedback').className='feedback '+(state.practiceAnswers[i]?'success':'bad');$('practiceFeedback').innerHTML=`${state.practiceAnswers[i]?'✓ Correct':'✕ Not quite'}. ${q.why}`;$('practiceNext').textContent='Next question'}else{$('practiceNext').textContent='Choose an answer'}opts.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{if(practiceAnswered)return;state.practiceAnswers[i]=+b.dataset.answer===q.correct;save();renderPractice()});$('practiceNext').onclick=()=>{if(!practiceAnswered)return;state.practiceIndex=(i+1)%D.practice.length;save();renderPractice()}}

  function renderInterview(){const i=state.interviewIndex%D.interview.length,q=D.interview[i];$('interviewRound').textContent=`ROUND ${i+1} · ${q.round.toUpperCase()}`;$('interviewCount').textContent=`${i+1} / ${D.interview.length}`;$('interviewQuestion').textContent=q.q;if(!interviewChecked){$('interviewAnswer').value='';$('interviewFeedback').classList.add('hidden');$('checkAnswer').textContent='Check my answer'}else{$('checkAnswer').textContent='Next question'}$('checkAnswer').onclick=()=>{if(interviewChecked){state.interviewIndex=(i+1)%D.interview.length;interviewChecked=false;save();renderInterview();return}checkInterview(q)};$('speakTip').onclick=()=>{const f=$('interviewFeedback');f.className='feedback warn';f.classList.remove('hidden');f.innerHTML=`<b>Answer tips:</b> ${q.tips}`}}
  function checkInterview(q){const text=$('interviewAnswer').value.trim().toLowerCase();if(!text){toast('Write your answer first');return}const hits=q.keywords.filter(k=>text.includes(k));const score=Math.round((hits.length/q.keywords.length)*100);state.interviewResults.push(score);if(state.interviewResults.length>20)state.interviewResults.shift();save();const f=$('interviewFeedback');f.className='feedback '+(score>=70?'success':score>=40?'warn':'bad');f.classList.remove('hidden');f.innerHTML=`<b>${score}% concept coverage</b><br>${hits.length?`Covered: ${hits.join(', ')}.`:'No key concepts detected yet.'}<br><br>${q.tips}`;interviewChecked=true;$('checkAnswer').textContent='Next question'}

  function renderSql(){renderTable('customersTable',D.sql.customers);renderTable('ordersTable',D.sql.orders);$('sqlResult').innerHTML='';$('loadSqlHint').onclick=()=>toast('Hint: SELECT + JOIN + SUM + GROUP BY + ORDER BY');$('resetSql').onclick=()=>{$('sqlEditor').value='SELECT customer_name, SUM(amount) AS total_sales FROM customers LEFT JOIN orders ON customers.id = orders.customer_id GROUP BY customer_name ORDER BY total_sales DESC;';$('sqlResult').innerHTML=''};$('runSql').onclick=runSql}
  function renderTable(id,rows){if(!rows.length){$(id).innerHTML='';return}const heads=Object.keys(rows[0]);$(id).innerHTML='<table><thead><tr>'+heads.map(h=>`<th>${esc(h)}</th>`).join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+heads.map(h=>`<td>${esc(r[h])}</td>`).join('')+'</tr>').join('')+'</tbody></table>'}
  function runSql(){const q=$('sqlEditor').value.toLowerCase().replace(/\s+/g,' ').trim();const expected=['select','join','sum','group by','order by'];const ok=expected.every(x=>q.includes(x))&&q.includes('customer');const result=$('sqlResult');if(!ok){result.innerHTML='<div class="result-bad"><b>Needs work.</b><br>For this challenge, your query should use SELECT, JOIN, SUM, GROUP BY and ORDER BY, and return customer-level sales.</div>';return}const totals={};D.sql.customers.forEach(c=>totals[c.name]=0);D.sql.orders.forEach(o=>{const c=D.sql.customers.find(x=>x.id===o.customer_id);if(c)totals[c.name]+=o.amount});const rows=Object.entries(totals).sort((a,b)=>b[1]-a[1]).map(([customer_name,total_sales])=>({customer_name,total_sales}));result.innerHTML='<div class="result-good"><b>Query pattern accepted ✓</b><div class="sql-output" style="margin-top:8px"><table><thead><tr><th>customer_name</th><th>total_sales</th></tr></thead><tbody>'+rows.map(r=>`<tr><td>${esc(r.customer_name)}</td><td>₹${r.total_sales.toLocaleString('en-IN')}</td></tr>`).join('')+'</tbody></table></div></div>';toast('SQL challenge passed ✓')}

  function renderPbi(){const i=state.pbiIndex%D.pbiCases.length,c=D.pbiCases[i];pbiAnswered=false;$('pbiCase').innerHTML=`<div class="eyebrow">CASE ${i+1} / ${D.pbiCases.length}</div><h3>${c.title}</h3><p>${c.context}</p><div class="case-choices">${c.choices.map((x,n)=>`<button class="case-choice" data-choice="${n}" type="button">${esc(x)}</button>`).join('')}</div><div id="caseFeedback" class="case-feedback"></div>`;$('pbiCase').querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{if(pbiAnswered)return;pbiAnswered=true;const n=+b.dataset.choice;b.classList.add(n===c.correct?'correct':'wrong');$('caseFeedback').innerHTML=`<b>${n===c.correct?'Good call ✓':'Not the best fit.'}</b> ${c.why}<br><button id="nextCase" class="btn primary small" style="margin-top:9px">Next case</button>`;$('nextCase').onclick=()=>{state.pbiIndex=(i+1)%D.pbiCases.length;save();renderPbi()}})}

  function renderProjects(){const list=$('projectList');list.innerHTML=D.projects.map(p=>{const done=state.projects[p.id]?.stepsDone?.length||0;return `<div class="project-card panel"><div class="project-top"><div><h3>${p.title}</h3><div class="project-tools">${p.tools}</div></div><span class="pill">${done}/${p.steps.length}</span></div><p class="project-summary">${p.summary}</p><div class="steps">${p.steps.map((s,i)=>`<div class="step ${i<done?'done':''}"><span class="dot">${i<done?'✓':i+1}</span><span>${s}</span></div>`).join('')}</div><div class="project-actions"><button class="btn small ghost" data-open-project="${p.id}" type="button">Open lab</button><button class="btn small" data-complete-project="${p.id}" type="button">${done===p.steps.length?'Replay pitch':'Complete next'}</button></div></div>`}).join('');list.querySelectorAll('[data-open-project]').forEach(b=>b.onclick=()=>showProject(b.dataset.openProject));list.querySelectorAll('[data-complete-project]').forEach(b=>b.onclick=()=>completeProjectStep(b.dataset.completeProject))}
  function completeProjectStep(id){const p=D.projects.find(x=>x.id===id);const s=state.projects[id]||{stepsDone:[]};if(s.stepsDone.length<p.steps.length)s.stepsDone.push(s.stepsDone.length);else toast('All steps complete — use Open lab for your pitch');state.projects[id]=s;save();renderProjects();toast(s.stepsDone.length===p.steps.length?'Project lab complete ✓':'Step complete ✓')}
  function showProject(id){const p=D.projects.find(x=>x.id===id);const d=$('projectDetail');const done=state.projects[id]?.stepsDone?.length||0;d.classList.remove('hidden');d.innerHTML=`<div class="eyebrow">${p.tools}</div><h3>${p.title}</h3><p>${p.summary}</p><div class="example">${esc(p.pitch)}</div><button id="closeProject" class="btn primary full" type="button">${done===p.steps.length?'Close lab':'Close'}</button>`;$('closeProject').onclick=()=>d.classList.add('hidden')}

  function renderRevision(){const due=D.lessons.filter(l=>!state.lessons[l.id]||!state.revisionDone[l.id]);$('revisionList').innerHTML=(due.length?due:D.lessons).map(l=>`<div class="revision-card panel"><span class="pill ${l.tag==='SQL'?'blue':'purple'}">${l.tag}</span><h3>${l.title}</h3><p>${l.desc}</p><div class="revision-question">${l.recall}</div><button class="btn small primary" data-revise="${l.id}" style="margin-top:10px" type="button">Mark recalled</button></div>`).join('');$('revisionList').querySelectorAll('[data-revise]').forEach(b=>b.onclick=()=>{state.revisionDone[b.dataset.revise]=true;save();renderRevision();toast('Recall saved ✓')})}

  let jobTab='tracker';
  document.querySelectorAll('[data-jobtab]').forEach(b=>b.onclick=()=>{jobTab=b.dataset.jobtab;document.querySelectorAll('[data-jobtab]').forEach(x=>x.classList.toggle('active',x.dataset.jobtab===jobTab));$('trackerTab').classList.toggle('hidden',jobTab!=='tracker');$('matcherTab').classList.toggle('hidden',jobTab!=='matcher')});
  function renderJobs(){const counts={Saved:0,Applied:0,Interview:0};state.jobs.forEach(j=>{if(counts[j.status]!==undefined)counts[j.status]++});$('jobSummary').innerHTML=`<div><strong>${counts.Saved}</strong><span>Saved</span></div><div><strong>${counts.Applied}</strong><span>Applied</span></div><div><strong>${counts.Interview}</strong><span>Interview</span></div>`;const list=$('jobList');list.innerHTML=state.jobs.length?state.jobs.map((j,i)=>`<div class="job-card panel"><div class="job-top"><div><h3>${esc(j.role)}</h3><p>${esc(j.company)}</p></div><span class="pill">${esc(j.status)}</span></div><p>${esc(j.notes||'No notes')}</p><div class="job-actions"><select data-status="${i}"><option ${j.status==='Saved'?'selected':''}>Saved</option><option ${j.status==='Applied'?'selected':''}>Applied</option><option ${j.status==='Interview'?'selected':''}>Interview</option><option ${j.status==='Rejected'?'selected':''}>Rejected</option><option ${j.status==='Selected'?'selected':''}>Selected</option></select><button class="btn small ghost" data-del="${i}" type="button">Delete</button></div></div>`).join(''):'<div class="panel" style="padding:15px"><b>No applications yet.</b><p class="muted">Add your first target role or use Job matcher.</p></div>';list.querySelectorAll('[data-status]').forEach(s=>s.onchange=()=>{state.jobs[+s.dataset.status].status=s.value;save();renderJobs();toast('Status updated')});list.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{state.jobs.splice(+b.dataset.del,1);save();renderJobs();toast('Application removed')});$('analyzeJob').onclick=analyzeJob}
  function analyzeJob(){const text=$('jdInput').value.toLowerCase();if(!text.trim()){toast('Paste a job description first');return}const skillMatches=D.skills.filter(s=>text.includes(s.toLowerCase()));const missing=['DAX','Tableau','Statistics','AWS','dbt','Git'].filter(s=>text.includes(s.toLowerCase())&&!D.skills.some(x=>x.toLowerCase()===s.toLowerCase()));const score=Math.min(100,Math.round((skillMatches.length/Math.max(1,D.skills.filter(s=>text.includes(s.toLowerCase())).length))*100));const required=skillMatches.length+missing.length;const relative=required?Math.round(skillMatches.length/required*100):0;$('matchResult').innerHTML=`<div class="panel" style="padding:14px"><div class="match-head"><div><div class="eyebrow">LOCAL MATCH ESTIMATE</div><h3 style="margin:0">Resume fit for this text</h3></div><div class="match-score">${relative}%</div></div><div class="match-grid"><div class="match-list"><strong>Matched</strong><p>${skillMatches.length?skillMatches.map(esc).join(' · '):'No resume skills detected yet.'}</p></div><div class="match-list"><strong>Watch for</strong><p>${missing.length?missing.map(esc).join(' · '):'No extra watch-list skill detected from this simple matcher.'}</p></div></div><div class="feedback warn" style="margin-top:9px"><b>Next move:</b> Use the matched skills as your interview drill list, then review any watch-list items before applying.</div></div>`}

  function renderProfile(){$('profileSkills').innerHTML=D.skills.map(s=>`<span class="chip">${esc(s)}</span>`).join('');$('profileProjects').innerHTML=D.projects.map(p=>`<div class="profile-project"><strong>${p.title}</strong><span>${p.tools}</span></div>`).join('')}

  $('addJobBtn').onclick=()=>$('jobModal').classList.remove('hidden');$('closeJobModal').onclick=()=>$('jobModal').classList.add('hidden');$('jobModal').onclick=e=>{if(e.target.id==='jobModal')$('jobModal').classList.add('hidden')};$('saveJob').onclick=()=>{const company=$('jobCompany').value.trim(),role=$('jobRole').value.trim();if(!company||!role){toast('Company and role are required');return}state.jobs.unshift({company,role,status:$('jobStatus').value,notes:$('jobNotes').value.trim()});['jobCompany','jobRole','jobNotes'].forEach(id=>$(id).value='');$('jobModal').classList.add('hidden');save();renderJobs();toast('Application saved ✓')};
  function renderAll(){renderHome();renderLessons();renderPractice();renderInterview();renderSql();renderPbi();renderProjects();renderRevision();renderJobs();renderProfile()}
  renderAll();
})();
