window.CAREER_DATA={
 skills:["SQL","MySQL","Power BI","Birst BI","Python","Pandas","NumPy","Advanced Excel","Data Cleaning","Data Validation","Dashboard Development","KPI Reporting","ETL Concepts","Data Warehousing","Star Schema","Fact & Dimension Modeling","Jupyter Notebook","Git","GitHub"],
 lessons:[
  {id:"sql",tag:"SQL",title:"SQL JOINs",time:"20 min",desc:"Connect tables and explain the business effect of the join type.",body:"Start by deciding which table must be preserved. INNER JOIN keeps matching rows. LEFT JOIN keeps every row from the left table and adds matches from the right. Then validate the result row count and totals.",example:"SELECT c.customer_name, SUM(o.amount) AS total_sales\nFROM customers c\nLEFT JOIN orders o ON o.customer_id=c.id\nGROUP BY c.customer_name\nORDER BY total_sales DESC;",recall:"When would you choose LEFT JOIN instead of INNER JOIN?"},
  {id:"pbi",tag:"Power BI",title:"KPI-first dashboard design",time:"20 min",desc:"Start with the decision, then choose the visual.",body:"Put 3–5 core KPIs first. Follow them with trend, segment and drill-down views. Keep labels, units and date logic consistent, and reconcile headline totals to a trusted source.",example:"Revenue | Orders | Average Order Value | Conversion Rate",recall:"What should be defined before adding charts to a stakeholder dashboard?"},
  {id:"python",tag:"Python",title:"Pandas data cleaning",time:"25 min",desc:"Turn messy rows into analysis-ready data with a repeatable flow.",body:"Use a simple sequence: inspect → identify missing/duplicate values → standardize data types → clean categories → validate counts and totals. The validation step is part of the analysis, not an optional afterthought.",example:"df.info()\ndf.isna().sum()\ndf.duplicated().sum()",recall:"Name three checks you would perform after cleaning a dataset."},
  {id:"model",tag:"Data Warehousing",title:"Star Schema",time:"20 min",desc:"Explain fact and dimension tables with confidence.",body:"A fact table stores measurable business events at a defined grain. Dimensions describe those events. In an interview, state the grain first, then explain the keys and measures.",example:"FactSales → DateKey, CustomerKey, ProductKey, Quantity, SalesAmount",recall:"What does the grain of a fact table tell you?"},
  {id:"quality",tag:"Data Quality",title:"Validation checks",time:"15 min",desc:"Protect the trustworthiness of reporting.",body:"Check duplicates, nulls in key fields, invalid dates, allowed categories, row counts and source-to-report reconciliation. Explain the action you take when a check fails.",example:"1. Duplicate business keys\n2. Null keys\n3. Invalid dates\n4. Total mismatch",recall:"Why is validation important before publishing a KPI dashboard?"}
 ],
 practice:[
  {topic:"SQL",q:"Which JOIN keeps every row from the left table?",options:["INNER JOIN","LEFT JOIN","RIGHT JOIN","CROSS JOIN"],correct:1,why:"LEFT JOIN preserves every left-table row and adds matches from the right."},
  {topic:"Modeling",q:"What should you define before designing a fact table?",options:["Font size","Grain","Dashboard theme","Company name"],correct:1,why:"Grain defines exactly what one fact row represents."},
  {topic:"Python",q:"Which pandas check counts missing values per column?",options:["df.shape","df.isna().sum()","df.describe()","df.head()"],correct:1,why:"isna() identifies missing values and sum() counts them by column."},
  {topic:"Power BI",q:"A KPI-first dashboard should start with:",options:["20 decorative charts","Core business KPIs","A logo","A pie chart"],correct:1,why:"The KPI layer keeps the dashboard decision-focused."},
  {topic:"Data Quality",q:"Which is a useful validation check?",options:["Changing colors","Checking duplicate keys","Adding pages","Renaming a column"],correct:1,why:"Duplicate-key checks catch common integrity problems."},
  {topic:"SQL",q:"Why can a JOIN create duplicate-looking rows?",options:["Because SQL is slow","Because of one-to-many relationships","Because SELECT is uppercase","Because tables have headers"],correct:1,why:"A one-to-many relationship can multiply rows when the join key matches multiple records."},
  {topic:"Python",q:"What is a useful next step after finding missing values?",options:["Ignore them always","Decide an evidence-based treatment","Change the chart color","Delete the database"],correct:1,why:"Treatment depends on business meaning: impute, exclude, flag or investigate."},
  {topic:"Power BI",q:"What should you validate before trusting a KPI?",options:["Its font","Its source and calculation logic","Its icon","Its page number"],correct:1,why:"A KPI is only useful when its source, definition and calculation are trusted."},
  {topic:"Modeling",q:"What does a dimension table usually contain?",options:["Only totals","Descriptive attributes","Only dashboard colors","SQL errors"],correct:1,why:"Dimensions describe entities such as customer, product or date."},
  {topic:"SQL",q:"Which clause sorts a result set?",options:["GROUP BY","ORDER BY","WHERE BY","SORT TABLE"],correct:1,why:"ORDER BY sorts the returned rows."}
 ],
 interview:[
  {round:"Technical",q:"Explain INNER JOIN vs LEFT JOIN and give a business example.",keywords:["inner","left","match","preserve","business"],tips:"Define each join, say which table is preserved, then give one business example."},
  {round:"Project",q:"Explain your Customer Sales Analytics project in 60 seconds.",keywords:["problem","sql","kpi","dashboard","insight"],tips:"Use this structure: problem → data → SQL/Power BI → KPI → insight/result."},
  {round:"Technical",q:"What is the grain of a fact table, and why does it matter?",keywords:["grain","row","measure","aggregation","fact"],tips:"Start with what one row represents. Then explain why the grain prevents incorrect aggregation."},
  {round:"Power BI",q:"How do you design a dashboard for a stakeholder who wants to know why sales changed?",keywords:["kpi","trend","segment","drill","business"],tips:"Lead with KPIs, then trend, then segment/drill-down views that answer why."},
  {round:"Data Quality",q:"How do you validate a report before sharing it?",keywords:["duplicate","null","reconcile","source","row"],tips:"Mention key-field checks plus a source-to-report reconciliation."},
  {round:"Python",q:"Describe a practical Pandas data-cleaning workflow.",keywords:["inspect","missing","duplicate","type","validate"],tips:"Use a sequence: inspect → missing/duplicates → data types → categories → validation."},
  {round:"Behavioral",q:"Tell me about a time you worked with a stakeholder on reporting requirements.",keywords:["requirement","stakeholder","clarify","deliver","feedback"],tips:"Keep it structured: situation → requirement → clarification → delivery → feedback."},
  {round:"Technical",q:"What are ETL concepts and where do they appear in analytics work?",keywords:["extract","transform","load","source","warehouse"],tips:"Explain the three stages and connect them to your reporting/data-processing workflow."}
 ],
 pbiCases:[
  {title:"Sales dropped 12% month over month",context:"Leadership wants the fastest way to see when the drop happened and then drill into the cause.",choices:["Line chart + KPI + drill-down","Pie chart only","Gauge only"],correct:0,why:"A trend shows when the decline happened; KPI gives magnitude; drill-down helps find drivers."},
  {title:"Compare revenue across regions",context:"The user needs easy comparison and wants to spot the strongest and weakest regions.",choices:["Sorted bar chart","Donut chart with 40 regions","Gauge"],correct:0,why:"A sorted bar chart supports clear category comparison and ranking."},
  {title:"Show daily transactions for a month",context:"The key question is the pattern over time, not category share.",choices:["Line chart","Pie chart","Single number card"],correct:0,why:"A line chart makes daily movement and peaks visible."}
 ],
 projects:[
  {id:"sales",title:"Customer Sales Analytics Dashboard",tools:"Birst BI · SQL · Power BI",summary:"KPI-driven business reporting and insights.",steps:["Define business questions","Clean and validate data","Write SQL for reporting","Build KPI layer","Add trend and segment views","Prepare 60-second explanation"],pitch:"I built a Customer Sales Analytics dashboard to turn sales data into KPI-driven business insights. I used SQL for reporting and Power BI/Birst BI for visualization, validated the data, and structured the dashboard around business questions."},
  {id:"credit",title:"Credit Risk & Loan Analytics Dashboard",tools:"Power BI · SQL · Excel",summary:"Lending analysis and KPI reporting.",steps:["Define lending KPIs","Inspect loan data","Clean and validate","Analyze risk segments","Build executive dashboard","Explain key drivers"],pitch:"I analyzed lending data and built KPI reporting for credit and loan analytics. I combined SQL/Excel analysis with Power BI visuals to identify useful patterns and communicate the results clearly."},
  {id:"salesperf",title:"Sales Performance Dashboard",tools:"Power BI · SQL",summary:"Automated reporting and sales trend tracking.",steps:["Define sales KPIs","Create reporting query","Validate totals","Build interactive report","Track trends","Explain automation"],pitch:"I built a Sales Performance dashboard to automate reporting and track sales trends. I used SQL for data preparation and Power BI for an interactive KPI-focused view."},
  {id:"power",title:"Power Consumption Analysis",tools:"Python · SQL",summary:"Energy usage pattern analysis.",steps:["Frame the business question","Inspect usage data","Clean data in Python","Analyze patterns","Validate results","Present insights"],pitch:"I analyzed power consumption patterns using Python and SQL, focusing on cleaning, analysis and clear analytical insights from usage data."}
 ],
 sql:{customers:[{id:1,name:"Acme Foods"},{id:2,name:"Northstar Retail"},{id:3,name:"Urban Mart"},{id:4,name:"Vertex Labs"}],orders:[{id:101,customer_id:1,amount:42000},{id:102,customer_id:1,amount:18000},{id:103,customer_id:2,amount:33000},{id:104,customer_id:3,amount:25000},{id:105,customer_id:2,amount:12000},{id:106,customer_id:4,amount:9000}]}
};
